/* Generated by Yosys 0.32+51 (git sha1 6405bbab1, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module pes_ripco(clk, reset, q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input clk;
  wire clk;
  output [1:0] q;
  wire [1:0] q;
  wire [1:0] q_int;
  input reset;
  wire reset;
  sky130_fd_sc_hd__clkinv_1 _11_ (
    .A(_06_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _12_ (
    .A(_07_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _13_ (
    .A(_08_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _14_ (
    .A(_08_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__dfrtp_1 _15_ (
    .CLK(q_int[0]),
    .D(_01_),
    .Q(q_int[1]),
    .RESET_B(_09_)
  );
  sky130_fd_sc_hd__dfrtp_1 _16_ (
    .CLK(clk),
    .D(_00_),
    .Q(q_int[0]),
    .RESET_B(_10_)
  );
  assign q = q_int;
  assign _06_ = q_int[0];
  assign _00_ = _02_;
  assign _07_ = q_int[1];
  assign _01_ = _03_;
  assign _08_ = reset;
  assign _09_ = _04_;
  assign _10_ = _05_;
endmodule
