/* Generated by Yosys 0.34+14 (git sha1 3e2279181, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module pes_ripco(clk, reset, q);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  input clk;
  wire clk;
  output [1:0] q;
  wire [1:0] q;
  reg [1:0] q_int;
  input reset;
  wire reset;
  sky130_fd_sc_hd__clkinv_1 _6_ (
    .A(_4_),
    .Y(_2_)
  );
  sky130_fd_sc_hd__clkinv_1 _7_ (
    .A(_5_),
    .Y(_3_)
  );
  always @(posedge q_int[0], posedge reset)
    if (reset) q_int[1] <= 1'h0;
    else q_int[1] <= _1_;
  always @(posedge clk, posedge reset)
    if (reset) q_int[0] <= 1'h0;
    else q_int[0] <= _0_;
  assign q = q_int;
  assign _4_ = q_int[0];
  assign _0_ = _2_;
  assign _5_ = q_int[1];
  assign _1_ = _3_;
endmodule
